services:
  web:
    image: nginx:alpine
    container_name: habit-tracker-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    restart: unless-stopped
    read_only: true

volumes:
  nginx_cache: